name: Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  dev:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        python: [ "3.10", "3.11", "3.12" ]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python}}

    - name: Run Python tests
      run: |
        python --version
        python -m pip install -r requirements.txt
        python -m unittest tests.test_codec
